### ISSUE TITLE
Using monotone_constraints with the method 'robust_exact'

### ISSUE THREAD

**Issue by Baptiste-Moreau** [chenhongge/RobustTrees#1]
**Environnment :**

Python 3.6 with ubuntu

**Bug :** 

The monotone_constraints parameters have unexpected behavior with the robust tree method.

**Condition :** 

XGBRegressor(monotone_constraints = monotone_constraints, tree_method = 'exact') works fine, but XGBRegressor(monotone_constraints = monotone_constraints, tree_method = 'robust_exact', robust_eps = 0) have different behavior. 

(First time posting an issue, let me know if you want more information, and thank you anyway for this great code that you've provided !)

**Comment by chenhongge** [comment]
Hi Baptiste-Moreau,  thanks for your interest to our project. Currently we do not recommend Python API to train models as it may not be fully supported yet in this repo. You may follow the instructions in README.md to use C++ executable created by ./build.sh to train the model. The .model file can then be loaded into Python for evaluations.

**Comment by huanzhang12** [comment]
@Baptiste-Moreau Could you please provide a minimum example and script to reproduce this issue? We can take a look. Thanks!

**Comment by huanzhang12** [comment]
@Baptiste-Moreau As suggested by @chenhongge, you can first try to reproduce the problem without Python API as we did not test Python API too much. However if it does not work even using the CLI, then there must be some issues we need to fix. Thanks!
